// src/utils/mockLots.js
// Shared mock data for all owner lot pages

export const INITIAL_LOTS = [
  {
    id: "lot-1",
    name: "Downtown Plaza",
    address: "123 Main St, Downtown",
    metrics: {
      totalRevenue: "$1,500",
      occupants: 12,
      reservations: 8,
      availableSpots: 6,
    },
    pricingRules: {
      baseRate: 2.5,
      durationMultiplier: 1.0,
      durationDiscountAfterHours: 4,
      durationDiscountPercent: 10,
      vehicleTypeMultipliers: { car: 1.0, motorcycle: 0.5, ev: 1.2 },
    },
    spots: [
      { id: "A1", status: "occupied",  vehicleType: "Car",        timeLimitMinutes: 120, driver: "Marcus Webb",    car: "Tesla Model 3",    plate: "ABC-1234", time: "2h 15m" },
      { id: "A2", status: "available", vehicleType: "All",        timeLimitMinutes: null, driver: null,            car: null,               plate: null,       time: null },
      { id: "A3", status: "reserved",  vehicleType: "Car",        timeLimitMinutes: 60,  driver: "Priya Kapoor",   car: "Honda Civic",      plate: "XYZ-5678", time: "Starts 3:30 PM" },
      { id: "A4", status: "occupied",  vehicleType: "Car",        timeLimitMinutes: null, driver: "James Rivera",  car: "Ford F-150",       plate: "LMN-9012", time: "45m" },
      { id: "A5", status: "available", vehicleType: "Motorcycle", timeLimitMinutes: 30,  driver: null,            car: null,               plate: null,       time: null },
      { id: "A6", status: "reserved",  vehicleType: "Car",        timeLimitMinutes: 120, driver: "Aisha Thompson", car: "Chevy Malibu",    plate: "QRS-3456", time: "Starts 4:00 PM" },
      { id: "B1", status: "available", vehicleType: "All",        timeLimitMinutes: null, driver: null,            car: null,               plate: null,       time: null },
      { id: "B2", status: "occupied",  vehicleType: "EV",         timeLimitMinutes: null, driver: "Leo Nguyen",    car: "Toyota Camry",     plate: "TUV-7890", time: "1h 30m" },
      { id: "B3", status: "occupied",  vehicleType: "Car",        timeLimitMinutes: 240, driver: "Sarah Kim",      car: "BMW 3 Series",     plate: "WXY-2345", time: "3h 05m" },
      { id: "B4", status: "available", vehicleType: "EV",         timeLimitMinutes: null, driver: null,            car: null,               plate: null,       time: null },
      { id: "B5", status: "occupied",  vehicleType: "Car",        timeLimitMinutes: 60,  driver: "Derek Jones",    car: "Dodge Charger",    plate: "ZAB-6789", time: "55m" },
      { id: "B6", status: "reserved",  vehicleType: "Car",        timeLimitMinutes: null, driver: "Nina Patel",    car: "Kia Sportage",     plate: "CDE-0123", time: "Starts 5:00 PM" },
      { id: "C1", status: "occupied",  vehicleType: "Car",        timeLimitMinutes: null, driver: "Omar Hassan",   car: "Mercedes C-Class", plate: "FGH-4567", time: "2h 40m" },
      { id: "C2", status: "available", vehicleType: "Motorcycle", timeLimitMinutes: 30,  driver: null,            car: null,               plate: null,       time: null },
      { id: "C3", status: "available", vehicleType: "All",        timeLimitMinutes: null, driver: null,            car: null,               plate: null,       time: null },
      { id: "C4", status: "occupied",  vehicleType: "Car",        timeLimitMinutes: 120, driver: "Zoe Martinez",   car: "Nissan Altima",    plate: "IJK-8901", time: "1h 10m" },
      { id: "C5", status: "reserved",  vehicleType: "EV",         timeLimitMinutes: null, driver: "Ben Chang",     car: "Hyundai Elantra",  plate: "LMO-2345", time: "Starts 6:00 PM" },
      { id: "C6", status: "available", vehicleType: "All",        timeLimitMinutes: null, driver: null,            car: null,               plate: null,       time: null },
    ],
  },
  {
    id: "lot-2",
    name: "Northside Garage",
    address: "88 Summit Ave, Northside",
    metrics: {
      totalRevenue: "$820",
      occupants: 5,
      reservations: 3,
      availableSpots: 4,
    },
    pricingRules: {
      baseRate: 3.0,
      durationMultiplier: 1.0,
      durationDiscountAfterHours: 3,
      durationDiscountPercent: 15,
      vehicleTypeMultipliers: { car: 1.0, motorcycle: 0.5, ev: 1.2 },
    },
    spots: [
      { id: "A1", status: "occupied",  vehicleType: "Car",        timeLimitMinutes: 60,  driver: "Tom Bradley",   car: "Subaru Outback",   plate: "AAA-0001", time: "30m" },
      { id: "A2", status: "available", vehicleType: "All",        timeLimitMinutes: null, driver: null,            car: null,               plate: null,       time: null },
      { id: "A3", status: "occupied",  vehicleType: "EV",         timeLimitMinutes: null, driver: "Susan Park",    car: "Chevy Bolt",       plate: "BBB-0002", time: "1h 05m" },
      { id: "A4", status: "available", vehicleType: "Motorcycle", timeLimitMinutes: 30,  driver: null,            car: null,               plate: null,       time: null },
      { id: "A5", status: "reserved",  vehicleType: "Car",        timeLimitMinutes: 120, driver: "Jake O'Brien",  car: "Honda CR-V",       plate: "CCC-0003", time: "Starts 2:00 PM" },
      { id: "A6", status: "available", vehicleType: "All",        timeLimitMinutes: null, driver: null,            car: null,               plate: null,       time: null },
      { id: "B1", status: "occupied",  vehicleType: "Car",        timeLimitMinutes: 240, driver: "Mia Chen",      car: "Toyota RAV4",      plate: "DDD-0004", time: "2h 00m" },
      { id: "B2", status: "available", vehicleType: "EV",         timeLimitMinutes: null, driver: null,            car: null,               plate: null,       time: null },
      { id: "B3", status: "reserved",  vehicleType: "Car",        timeLimitMinutes: 60,  driver: "Rachel Green",  car: "Ford Escape",      plate: "EEE-0005", time: "Starts 4:30 PM" },
      { id: "B4", status: "available", vehicleType: "All",        timeLimitMinutes: null, driver: null,            car: null,               plate: null,       time: null },
      { id: "B5", status: "occupied",  vehicleType: "Motorcycle", timeLimitMinutes: 30,  driver: "Luis Gomez",    car: "Yamaha MT-07",     plate: "FFF-0006", time: "15m" },
      { id: "B6", status: "available", vehicleType: "All",        timeLimitMinutes: null, driver: null,            car: null,               plate: null,       time: null },
    ],
  },
];
